# Generated by Django 3.0.5 on 2020-04-17 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=200)),
                ('des', models.TextField()),
                ('img', models.ImageField(upload_to='pics')),
                ('no_of_courses', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=200)),
                ('img', models.ImageField(upload_to='pics')),
                ('des', models.TextField()),
                ('price', models.IntegerField()),
                ('curr_students', models.IntegerField()),
                ('faculty_name', models.CharField(max_length=200)),
                ('faculty_role', models.CharField(max_length=200)),
                ('faculty_img', models.ImageField(upload_to='pics')),
            ],
        ),
    ]
