# Generated by Django 3.0.5 on 2020-04-18 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CourseUni', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='des',
            field=models.TextField(max_length=45),
        ),
        migrations.AlterField(
            model_name='courses',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
