# Generated by Django 3.0.5 on 2020-04-19 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CourseUni', '0002_auto_20200418_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='des',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='courses',
            name='des',
            field=models.CharField(max_length=40),
        ),
    ]
