# Generated by Django 3.0.5 on 2020-04-19 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CourseUni', '0005_auto_20200419_1502'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup',
            name='uname',
        ),
    ]
