# Generated by Django 3.0.5 on 2020-04-19 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CourseUni', '0006_remove_signup_uname'),
    ]

    operations = [
        migrations.DeleteModel(
            name='signup',
        ),
    ]
