# Generated by Django 3.0.5 on 2020-04-19 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CourseUni', '0007_delete_signup'),
    ]

    operations = [
        migrations.CreateModel(
            name='teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('number', models.CharField(max_length=10)),
                ('course', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=40)),
                ('course_file', models.FileField(upload_to='pics')),
            ],
        ),
    ]
